spring:
  profiles:
    active: dev
foo:
    version: 1

---
spring:
  profiles: dev
  application:
        name: springcloud-config-client-dev
server:
  port: 8084
  
---
spring:
  profiles: test
  application:
        name: springcloud-config-client-test
server:
  port: 8083