spring:
  profiles:
    active: dev
eureka:
    client:
        service-url:
            defaultZone: http://localhost:70001/eureka/

---
spring:
  profiles: dev
  application:
        name: springcloud-config-client-dev
server:
  port: 8084
  
---
spring:
  profiles: test
  application:
        name: springcloud-config-client-test
server:
  port: 8083
    
